services:
  db:
    image: postgres
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-test
      POSTGRES_DB: dev-db
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080