name: Dev Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        rust-version: stable
      
    - name: Project Build
      run: cargo build --release

    - name: Run Tests
      run: cargo test
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      
    - name: Build and Push Docker Image
      run: |
        docker build -t evilgenius13/kt2:dev-${{ github.sha }} .
        docker push evilgenius13/kt2:dev-${{ github.sha }}
    
    - name: Notify Discord
      uses: th0th/notify-discord@v0.4.1
      if: ${{ always() }}
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_JOB_STATUS: ${{ job.status }}